### ISSUE TITLE
Choice field does not render choices

### ISSUE THREAD

**Issue by eddiejaoude** [adamquaile/AdamQuaileFieldsetBundle#4]
```php
$builder
            ->add(
                'program_group',
                'fieldset',
                [
                    'label'  => false,
                    'legend' => 'Program details',
                    'fields' => [
                        [
                            'name'    => 'name',
                            'type'    => 'choice',
                            'attr'    => ['label' => false],
                            'expanded'  => true,
                            'multiple'  => true,
                            'choices' => [
                                'Analytical'                            => 'Analytical',
                                'Human Resources'                       => 'Human Resources',
                                'Government Communication Service'      => 'Government Communication Service',
                                'Northern Ireland'                      => 'Northern Ireland',
                                'Generalist'                            => 'Generalist',
                                'Commercial and Finance'                => 'Commercial and Finance',
                                'Digital and Technology'                => 'Digital and Technology',
                                'European'                              => 'European',
                                'Summer Diversity Internship Programme' => 'Summer Diversity Internship Programme',
                                'Early Diversity Internship Programme'  => 'Early Diversity Internship Programme',
                            ],
                        ],
                    ]
                ]
            );
```

**Comment by eddiejaoude** [comment]
Output:

```html
<select id="csr_dm_program_program_group_name" name="csr_dm_program[program_group][name]" class="form-control"></select>
```

**Comment by SpartakusMd** [comment]
@eddiejaoude, you are trying to send attributes outside of the *attr* array ! I fixed your code.

    $builder
        ->add(
            'program_group',
            'fieldset',
            [
                'label'  => false,
                'legend' => 'Program details',
                'fields' => [
                    [
                        'name'    => 'name',
                        'type'    => 'choice',
                        'attr'    => [
                            'label' => false,
                            'expanded'  => true,
                            'multiple'  => true,
                            'choices' => [
                                'Analytical'                            => 'Analytical',
                                'Human Resources'                       => 'Human Resources',
                                'Government Communication Service'      => 'Government Communication Service',
                                'Northern Ireland'                      => 'Northern Ireland',
                                'Generalist'                            => 'Generalist',
                                'Commercial and Finance'                => 'Commercial and Finance',
                                'Digital and Technology'                => 'Digital and Technology',
                                'European'                              => 'European',
                                'Summer Diversity Internship Programme' => 'Summer Diversity Internship Programme',
                                'Early Diversity Internship Programme'  => 'Early Diversity Internship Programme',
                            ],
                        ]
                    ],
                ]
            ]
        );

**Comment by adamquaile** [comment]
@SpartakusMd Thanks for responding - that's exactly right. 
@eddiejaoude Sorry you had to wait - I completely missed this!

**Comment by eddiejaoude** [comment]
No worries, it happens.
