### ISSUE TITLE
"Choice" options are empty

### ISSUE THREAD

**Issue by blackparadox** [adamquaile/AdamQuaileFieldsetBundle#6]
Hey, I've got a problem similar to issue #4; I can't get select boxes to render their content, and I can't work out why.
I've triple checked the format (as per the other issues resolution) and unless I'm being blind, I can't see anything wrong with it.

The options I'm passing to $buider->add() are as follows:
```
$builder->add(
    'applicant_details',
    'fieldset',
    array(
        'label'  => false,
        'legend' => 'Your Details',
        'fields' => array(
            array(
                'name' => 'title',
                'type' => 'choice',
                'attr' =>  array(
                    'label'   => 'Title',
                    'choices' => array(
                        'Mr'   => 'Mr',
                        'Mrs'  => 'Mrs',
                        'Miss' => 'Miss',
                        'Ms'   => 'Ms',
                        'Mx'   => 'Mx',
                    ),
                ),
            ),
        ),
    )
```

Can anyone see where I'm going wrong?

**Comment by blackparadox** [comment]
...after much digging around, I've eliminated the fieldset bundle as the cause of this issue - still no closer to fixing it however.

**Comment by adamquaile** [comment]
Is it possible to post any more code somehow, I can try and help. Also, have a look at the form tab on the symfony console bar and see if that gives any clues. Are the choices as you expect in there? 

http://symfony.com/blog/new-in-symfony-2-4-great-form-panel-in-the-web-profiler

**Comment by blackparadox** [comment]
Hey, thanks for coming back to me.
I got to the bottom of it in the end, a third-party mod to the field templates (that used old symfony code) was messing it up if you used placeholders in select boxes.
Deleted it and wrote my own version based on the default block and it's all sorted now.

**Comment by adamquaile** [comment]
Great! Glad it's all sorted.
