### ISSUE TITLE
Unable to target child form elements with $form->get()

### ISSUE THREAD

**Issue by blackparadox** [adamquaile/AdamQuaileFieldsetBundle#7]
Not sure if this is a bug, or me going about things the wrong way, but as I understand it; when you want to target a form element you can use $form->get(field_name) - where "$form" is the Form object created by Controller->createForm($type, $entity).

I can target anything that is added directly though FormBuilderInterface->add(name, type, options) but If I try to target anything that is a child of a fieldset created with this bundle (using the same string as set in the fieldset[options][fields][name] variable), symfony throws an error of "Child "field_name" does not exist.

Is this a limitation of the FieldsetBundle, or an example of my ignorance of Symfony's methods?
How can I access the underlying object for the child element?

**Comment by adamquaile** [comment]
You should be able to access the nested elements. Could you post some code?

**Comment by blackparadox** [comment]
aha! So I have to call get() on the fieldset, and then get() again on the returned object.
Little bit of a pain to loop through from the way the logic is structured, but should be able to get it working now.

**Comment by adamquaile** [comment]
Glad you got it working.. Feel free to post you're working code, maybe there's an easier way.
